default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>


development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] || "postgres://@localhost/similarity_score_development" %>


test:
  <<: *default
  url: <%= ENV['TEST_DATABASE_URL'] || "postgres://@localhost/similarity_score_test" %>
